name: projet2cp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_database: ^10.3.8
  firebase_storage: ^11.5.6

  # Charts
  fl_chart: ^0.66.0
  syncfusion_flutter_charts: ^24.1.41

  # UI & Utils
  provider: ^6.1.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - Assets/

  fonts:
    - family: VeronaSerial
      fonts:
        - asset: fonts/verona-serial-bold.ttf
    - family: SpaceGrotesk
      fonts:
        - asset: fonts/spacerotesk/SpaceGrotesk-VariableFont_wght.ttf